"use client";

import { CheckCircle2, Circle, Clock, Lock } from "lucide-react";
import type { PayrollRun } from "@/lib/types/payroll";

interface PayrollRunPipelineProps {
  run: PayrollRun;
}

export function PayrollRunPipeline({ run }: PayrollRunPipelineProps) {
  const steps = [
    {
      label: "Draft generated",
      status: "DRAFT",
      desc: `Generated by User`,
      time: run.createdAt,
    },
    {
      label: "Submitted for Review",
      status: "UNDER_REVIEW",
      desc: run.notes || "Pending verification",
      time: run.updatedAt,
    },
    {
      label: "Approved",
      status: "APPROVED",
      desc: run.reviewedBy ? `Reviewed` : "Awaiting final approval",
      time: run.reviewedAt,
    },
    {
      label: "Locked & Amortized",
      status: "LOCKED",
      desc: run.approvedBy ? `Authorized` : "Locked for payments",
      time: run.lockedAt,
    },
  ];

  const getStepState = (stepStatus: string, currentStatus: string) => {
    const order = ["DRAFT", "UNDER_REVIEW", "APPROVED", "LOCKED"];
    const stepIdx = order.indexOf(stepStatus);
    const currIdx = order.indexOf(currentStatus);

    if (stepIdx < currIdx) return "COMPLETED";
    if (stepIdx === currIdx) return "ACTIVE";
    return "PENDING";
  };

  return (
    <div className="rounded-xl border border-[#d7e8d0] bg-white p-6 shadow-sm">
      <h3 className="text-sm font-bold text-[#1b3a1f] uppercase tracking-wider mb-6">Payroll Workflow Status</h3>
      <div className="relative flex flex-col gap-6 md:flex-row md:justify-between md:gap-2">
        {/* Connector line for large screens */}
        <div className="absolute left-6 top-6 hidden h-0.5 w-[85%] bg-gray-200 md:block" />

        {steps.map((step, idx) => {
          const state = getStepState(step.status, run.status);
          
          return (
            <div key={idx} className="relative z-10 flex flex-1 flex-col items-start text-left md:items-center md:text-center">
              <div className="flex items-center gap-3 md:flex-col md:gap-2">
                {state === "COMPLETED" && (
                  <div className="flex h-10 w-10 items-center justify-center rounded-full bg-emerald-50 text-emerald-600 border border-emerald-200">
                    <CheckCircle2 className="h-5 w-5" />
                  </div>
                )}
                {state === "ACTIVE" && (
                  <div className="flex h-10 w-10 animate-pulse items-center justify-center rounded-full bg-green-50 text-green-600 border border-green-200">
                    <Clock className="h-5 w-5" />
                  </div>
                )}
                {state === "PENDING" && (
                  <div className="flex h-10 w-10 items-center justify-center rounded-full bg-gray-50 text-gray-400 border border-gray-200">
                    <Circle className="h-5 w-5" />
                  </div>
                )}

                <div>
                  <p className="text-sm font-semibold text-[#1b3a1f]">{step.label}</p>
                  <p className="mt-0.5 text-xs text-gray-500">{step.desc}</p>
                  {step.time && (
                    <p className="mt-1 text-[10px] text-gray-400 tabular-nums">
                      {new Date(step.time).toLocaleString()}
                    </p>
                  )}
                </div>
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
}
