CREATE TABLE "pay_heads" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"code" varchar(50) NOT NULL,
	"name" varchar(255) NOT NULL,
	"type" varchar(20) NOT NULL,
	"effect_on_tax" boolean DEFAULT false NOT NULL,
	"calc_basis" varchar(50) NOT NULL,
	"calc_parameter" varchar(50) NOT NULL,
	"calc_percent" numeric(5, 2) DEFAULT '0' NOT NULL,
	"applicable_department_ids" text[] DEFAULT ARRAY[]::text[] NOT NULL,
	"applicable_designation_ids" text[] DEFAULT ARRAY[]::text[] NOT NULL,
	"is_festival_allowance" boolean DEFAULT false NOT NULL,
	"is_absent_deduct" boolean DEFAULT false NOT NULL,
	"is_ot_head" boolean DEFAULT false NOT NULL,
	"is_leave_head" boolean DEFAULT false NOT NULL,
	"is_tds_head" boolean DEFAULT false NOT NULL,
	"is_pf_head" boolean DEFAULT false NOT NULL,
	"is_ssf_head" boolean DEFAULT false NOT NULL,
	"is_remote_allowance" boolean DEFAULT false NOT NULL,
	"is_cit_head" boolean DEFAULT false NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "pay_heads_code_unique" UNIQUE("code")
);
